### ISSUE TITLE
Pagination of nested lists doesn't work

### ISSUE THREAD

**Issue by MorFix** [aws-amplify/amplify-swift#3093] opened 2023-07-17 07:56 UTC
### Describe the bug

When you query the AppSync GraphQL endpoint for something that has nested, paginated list you have no working way of retrieving next pages of the nested list.

Consider this example schema

```
type Todo @model {
  name: String
  notes: [Note] @hasMany
}

type Note @model {
  title: String
  content: String!
  todo: Todo @belongsTo
}
```

Let's say we have an instance of `Todo` that has 2000 notes connected to it. A typical GraphQL query for `Todo` would look like:

```
query listTodos {
  items {
    notes {
      items {
        id
        title
        content
      }
      nextToken
    }
  }
  nextToken
}
```

And a typical `Todo` item response would be:

```
{
    "name": "My Long TODO",
    "notes": {
      "nextToken": "ABCDEFGHIJK", // This is the problematic token
      "items": [...]
    }
}
```

Now, in order to use "ABCDEFGHIJK" as a token, one should send the following query body:
```
query listTodos {
  items {
    notes(nextToken: "ABCDEFGHIJK") { // Here is the change
      items {
        ....
      }
    }
  }
}
```

Now, In Swift, the `notes` list is expressed as a `List<Note>` in which you can call `fetch()` to have the list and `getNextPage()` to query for the next page. When you call `getNextPage()` the following query is being sent:
```
query listNotes { // Listing ALL the notes from ALL the todos without any filtering (?!)
  items {
    ...
  }
}
```
With variables of `nextToken = "ABCDEFGHIJK"`

Two major problems with it:
1. It doesn't work. The query produces the following GraphQL error: `Invalid pagination token given`.
This happens because we use a token that was generated in `Todo.notes` resolver in a `Query.listNotes` resolver.
This isn't possible according to the [AppSync docs](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html):
> Also note that these pagination tokens cannot be used across different resolvers.

2. It doesn't query notes that are related to the parent `Todo`.

It seems that something is missing from the implementation of `getNextPage()`.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create a schema similar to the described above
2. Insert some data to make many notes connected to one `Todo` item
3. Generate Swift models
3. Call `let todo = await Amplify.API.Query(Todo.self)` 
4. Call `await todo.notes?.getNextPage()`
5. It doesn't work
```

### Expected behavior

The above use case, which seems pretty straight-forward, should work.

### Amplify Framework Version

2.*

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.*

### CLI version

12.*

### Xcode version

14.*

### Is this a regression?

No

### Platforms

iOS

### OS Version

iOS 16

### Device

any

### Specific to simulators

No

**Comment by harsh62** [comment] 2023-07-17 17:37
Thanks for opening the issue. Our team will look into the issue and provide an update as soon as we have one.

**Comment by MorFix** [comment] 2023-08-14 11:36
@lawmicha Hello, thanks for your comment.
What you described is exatctly what we've been doing (including the flag, models generation and the exact API call).
If `notes` has more than one page, 2 problems occur:

> 1. It doesn't work. The query produces the following GraphQL error: `Invalid pagination token given.`
> This happens because we try to use a token that was generated in `Todo.notes` resolver in a `Query.listNotes` resolver.
> This isn't possible according to the [AppSync docs](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html):
> > Also note that these pagination tokens cannot be used across different resolvers.
> 
> 2. It doesn't query notes that are related to the parent Todo.

**Comment by lawmicha** [comment] 2023-08-17 00:20
Hey @MorFix, thanks for the details so far, can you give me the exact API call you are making? I'm having troubles following how you are getting the error. Here's what I tried:

1. Querying for Todos 

```swift
let request = GraphQLRequest<Todo>.list(Todo.self)
```

```
GraphQLRequest<List<Todo>>(apiName: nil, document: "query ListTodos($limit: Int) {
  listTodos(limit: $limit) {
    items {
      id
      createdAt
      name
      updatedAt
      __typename
    }
    nextToken
  }
}", variables: Optional(["limit": 1000]), responseType: Amplify.List<workingWithFiles.Todo>, decodePath: Optional("listTodos"), options: nil)
```

In this case, `todo.notes.fetch()` will make a listNotes with a filter on todo.id, and selection set will contain nextToken. The nextToken in the response gets stored in the list to perform `hasNextPage()` and `getNextPage()`.

2. Querying for Todos and include Notes 

```swift
let request = GraphQLRequest<Todo>.list(Todo.self) { todo in [todo.notes] }
```

```
GraphQLRequest<List<Todo>>(apiName: nil, document: "query ListTodos($limit: Int) {
  listTodos(limit: $limit) {
    items {
      id
      createdAt
      name
      updatedAt
      __typename
      notes {
        items {
          id
          content
          createdAt
          title
          updatedAt
          todo {
            id
            __typename
          }
          __typename
        }
      // Missing nextToken under `notes`.
      }
    }
    nextToken
  }
}", variables: Optional(["limit": 1000]), responseType: Amplify.List<workingWithFiles.Todo>, decodePath: Optional("listTodos"), options: nil)

```

The problem here is that `nextToken` isn't even added for notes (see in-line comment above). I'm working on fixing that in  https://github.com/aws-amplify/amplify-swift/pull/3161 . But I'm concerned if this fix will even work, as you described, that if the `todo.notes.nextToken` is used for a `listNotes` query, it will not work and fail with `Invalid pagination token given`

**Comment by lawmicha** [comment] 2023-08-25 17:02
After further discussion with the team, we have found a limitation with querying data using a custom selection set with a depth of 2. When performing a query including the associated data of a has-many relationship, the has-many list cannot paginate since the nextToken information is not added. Even if it was added, the nextToken pretains to the original query and cannot be used in the associated model's query from the List APi.

The workaround here is to perform a query without includes, then load the has-many on-demand, then you will be able to paginate on the has-many associated data.

**Comment by lawmicha** [comment] 2023-08-29 15:43
https://github.com/aws-amplify/docs/pull/5822

**Comment by lawmicha** [comment] 2023-09-15 17:32
@MorFix Closing this issue since we have identified the root cause to the problem. Feel free to let us know if something isn't clear. 

To summarize:
- If using custom selection sets to include the nested list, then there is no pagination support for that list. You can explicitly make a call to rehydrate the list, by calling `Amplify.API.query(requestL .list(YourList.self, where: YourList.parentId == parent.id)` to get pagination support
- alterantively, you can query for the parent model, and lazy load the has-many children, then you can paginate on the list. 
- If this doesn't fit your use case, you can also define a custom GraphQL request, and that will require some extra work as well to get the right decoding type to use.

**Closed by lawmicha** 2023-09-15 17:32 UTC
Labels: bug, api
