### ISSUE TITLE
Crash in AWSDataStorePlugin

### ISSUE THREAD

**Issue by voicesmackiev** [aws-amplify/amplify-swift#2841] opened 2023-03-30 16:01 UTC
### Describe the bug

Amplify crashes with error 'Swift runtime failure: Unexpectedly found nil while implicitly unwrapping an Optional value + 0 (AWSDataStorePlugin+DataStoreBaseBehavior.swift:0)'
There are no steps to reproduce, crash logs are obtained from AppStore users. See attached examples of crashes.

[Archive.zip](https://github.com/aws-amplify/amplify-swift/files/11113371/Archive.zip)

### Steps To Reproduce

```swift
There are no steps to reproduce. Apps saves/queries data to DataStore; starts/stops data syncing; uploads/downloads/removes files to Storage
```

### Expected behavior

No crashes in Amplify

### Amplify Framework Version

1.28.1

### Amplify Categories

API, Auth, DataStore, Storage

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

10.7.3

### Xcode version

14.2 (14C18)

### Is this a regression?

No

### Device

different iPads and iPhones

### iOS Version

iOS 15.x-16.x

**Comment by royjit** [comment] 2023-03-30 16:20
Look like the crash is coming from this line:  https://github.com/aws-amplify/amplify-swift/blob/e4c57368232c2365a6ed069430ce6e99c900d9c8/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin%2BDataStoreBaseBehavior.swift#L348 

with the runtime error:
```
Swift runtime failure: Unexpectedly found nil while implicitly unwrapping an Optional value + 0 (AWSDataStorePlugin+DataStoreBaseBehavior.swift:0)
```

which leads to believe that `storageEngine` is nil when this line of code is executed. Do you call any of these apis in your app from Datastore: `clear(), stop(), reset()` ?

**Comment by voicesmackiev** [comment] 2023-03-30 16:37
Hi @royjit, yes, we may call clear() and stop()

**Comment by royjit** [comment] 2023-03-30 17:37
Thank you for the prompt reply, we are looking into the issue and will provide update here when we have more info.

**Comment by nonameplum** [comment] 2023-04-06 13:01
He experience the same issue on Amplify 2.7.1. It seems like the issue is especially repeatable if we make many `Task { Amplify.DataStore.save(...)`. Could be a problem that meanwhile Amplify internally is scheduling the synchronization with the backend which causes to `nil`-out `storageEngine` property for the ongoing `save`/`query`... calls?

**Comment by fzy-spyro** [comment] 2023-04-12 10:25
Any update on the crash issue? I am also seeing this

**Comment by harsh62** [comment] 2023-04-12 14:16
Thank you for your patience. The team is actively working on a fix and needs to go through an internal review. We will post an update on the issue as soon as we have one.

**Comment by 5d** [comment] 2023-05-26 17:31
Hi @voicesmackiev @fzy-spyro @nonameplum , 

The potential fix for this problem has been merged into both the legacy v1 and the main branches. Would you mind testing the most recent code and verifying if it resolves your issue?

**Comment by nonameplum** [comment] 2023-06-05 08:56
@5d We see an improvement. We don't see a crash in a code base that before the fix was often.

**Closed** 2023-06-16 18:03 UTC
Labels: bug, datastore

**Comment by fzy-spyro** [comment] 2023-08-22 10:36
Hey @5d 

we have started seeing the issue again. we're using version: 2.11.5

**Comment by 5d** [comment] 2023-08-25 18:25
Hi @fzy-spyro ,

Could you please create a new issue and include additional information such as the version, verbose logs, or a crash report?

**Comment by fzy-spyro** [comment] 2023-08-31 09:38
@5d thanks, I've raised https://github.com/aws-amplify/amplify-swift/issues/3198
