### ISSUE TITLE
Why is file upload so incredibly slow?

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-swift#1542] opened 2021-11-22 05:53 UTC
I am uploading files that are about 300-400kb in size.  The average upload time for a single file is 30 seconds which is unacceptable.  How can I improve this?  I'm suing the following code from your example to upload and have a fast stable wifi connection.

```
let dataString = "My Data"
let data = dataString.data(using: .utf8)!  
let storageOperation = Amplify.Storage.uploadData(key: "ExampleKey", data: data)
let progressSink = storageOperation.progressPublisher.sink { progress in print("Progress: \(progress)") }
let resultSink = storageOperation.resultPublisher.sink {
    if case let .failure(storageError) = $0 {
        print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
    }
}
receiveValue: { data in
    print("Completed: \(data)")
}
```

**Comment by royjit** [comment] 2021-11-25 01:34
Are you seeing 30 seconds for all file uploads or just the first try? The first try might include different api calls to fetch AWS credentials which might take a few seconds more. The subsequent upload calls should be faster.

**Comment by alionthego** [comment] 2021-12-01 02:03
I'm seeing a very long period for the first try and then somewhat long periods for subsequent uploads.  Even not being the first upload the time it takes is really unacceptable.  The same data count size to lambda or api upload is much much faster.

**Comment by alionthego** [comment] 2021-12-05 04:54
Not sure how these upload times to S3 are acceptable.  Files just 2-3 MB take over 30 seconds.  Unacceptable.

**Comment by brennanMKE** [comment] 2021-12-07 19:11
@alionthego When this is happening can you count up the number of active threads? 

We have been working on some performance improvements and one was just merged which could help with your issue. If other work is in progress and it is causing threads to be blocked it could explain why this operation is delayed. See the issues mentioned at the bottom of the PR below. This update will be included in the next release.

[#3872](https://github.com/aws-amplify/aws-sdk-ios/pull/3872)

**Comment by diegocstn** [comment] 2021-12-21 01:47
@alionthego we've released the performance improvements of [#3872](https://github.com/aws-amplify/aws-sdk-ios/pull/3872) with Amplify [v1.18.1](https://github.com/aws-amplify/amplify-ios/releases/tag/v1.18.1).
Let us know if it helps with your issue.

**Comment by alionthego** [comment] 2022-02-27 11:44
I am using latest sdk and the s3 file upload is still unacceptably slow.  it takes about 30 seconds to upload 400 kb.

**Comment by sagarjoshi** [comment] 2022-04-10 01:21
same issue, upload is slow

**Comment by orlaqp** [comment] 2022-05-07 15:57
I am seeing the same issue :-|

**Comment by staticVoidMan** [comment] 2022-06-01 08:34
Same issue. Upload is slow. !

Actual Example (~1mb file took ~39seconds):

```
func uploadData(data: Data, key: String) {
    let startDate = Date()
    print(data) // 991691 bytes

    let options = StorageUploadDataRequest.Options(accessLevel: .private)

    Amplify.Storage.uploadData(key: key, data: data, options: options) { result in
        let endDate = Date().timeIntervalSince(startDate)
        print("!@", endDate) // 38.75
    }
}
```

**Comment by staticVoidMan** [comment] 2022-06-02 16:00
@atierian Hey! thanks for reverting.
We are using Amplify via SPM, and the version we are at is `1.25.0`.

As for the `amplifyconfiguration.json`, the `region` is `us-west-2` but we would be located `us-east`.
I first did doubt the region but our Android counterpart team is using the same `us-west-2` but not facing any upload speed issues.

**Comment by anuragsingla123** [comment] 2022-07-28 08:13
@atierian I am facing the same issue as well. I am using the latest Amplify version 1.27.1 for iOS but it still takes 2-3 minutes in uploading a small file. The S3 bucket is currently in us-east-1 region.

**Comment by atierian** [comment] 2022-07-28 08:46
Thanks for letting us know. 
Slow uploads / transfers is actively being investigated. We'll follow up on this issue with any updates.

**Comment by dhaval-dobariya** [comment] 2022-11-12 07:30
I am facing same issue, any solution is there?

**Comment by jcjimenez** [comment] 2022-11-15 22:14
@alionthego @anuragsingla123 @dhaval-dobariya @sagarjoshi @staticVoidMan I'm picking up this investigation but haven't been able to reproduce this on my end (including using Apple's Network Link Conditioner). Would you please contact me directly to see if we can have a call to diagnose? Thanks.

**Comment by alionthego** [comment] 2022-11-15 22:25
Try a request from a different region.  Such as servers in Virginia and client in Hong Kong

**Comment by jcjimenez** [comment] 2022-11-16 20:50
Just writing to update you all on progress: I do see very slow upload times (about 2 minutes for a 1.1MB file) being in Texas and uploading to AWS regions such as Mumbai. I'm taking a deeper dive to figure out if there is a root cause (in the library or SDK) apart from the physical distance.

**Comment by vish7** [comment] 2022-11-21 14:02
Hi, I am facing the same issue. I am using Amplify 1.28.3 version. 
11 MB video file is taking 6 -7 minutes to upload.
But in AWS SDK video upload was working fine with AWSS3TransferUtility class. 
Code:

let fileNameKey = "testing_upload_video_3.mov"
        let filePath = Bundle.main.url(forResource: "testing_upload_video_2", withExtension: "MOV")
        
        guard let filename = filePath
        else { return }

        let storageOperation = Amplify.Storage.uploadFile(
            key: fileNameKey,
            local: filename,
            progressListener: { progress in
                print("Progress: \(progress)")
            }, resultListener: { event in
                switch event {
                case let .success(data):
                    print("Completed: \(data)")
                case let .failure(storageError):
                    print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
                }
            }
        )

**Comment by jcjimenez** [comment] 2022-11-28 17:47
Thank you for your patience, I've submitted the pull request above which the team will discuss.

**Comment by nivritgupta** [comment] 2023-01-11 08:14
is there any solutions for this problem , upload time is incredibly slow for me as well , 3 MB file size takes more then 8 to 9  minutes time for upload. 😔😔

**Comment by OldChicken** [comment] 2023-03-08 02:15
is there any solutions for this problem , upload time is incredibly slow for me as well , 3 MB file size takes more then 8 to 9 minutes time for upload. 😔😔   + 1

**Comment by babinowich** [comment] 2023-03-09 14:14
We have a use case with large, 50-100MB uploads which can take between 0:00:15 and 1:55:00 on gigabit connections. Even worse, we get no status back as far as the progress in fractionCompleted reliably. It can take 5-10 minutes before the user gets notification at all of any progress, forcing us to fake a 1% increment of progress to keep the user on the page.

Therefore we see two core issues with Amplify swift:
1) Extremely unreliable upload speeds with the same file on the same internet connection on the same device in the same hour
2) The above would be less painful if we had reliable progress updates, but we see unusable upload progress for consumers

At this point, we may be forced to consider alternative storage solutions that are responsive and attentive to known issues that have been stagnating for **5 months.**

Code:

`    static func uploadPreSignedFile(key: String, fileUrl: URL) -> StorageUploadFileTask {
        let key = "uploads/\(key).zip"
        return Amplify.Storage.uploadFile(key: key, local: fileUrl, options: .init(
            contentType: "application/zip"
        ))
    }`

`        let uploadTask = StorageHelper.uploadPreSignedFile(key: key, fileUrl: fileUrl)
`

`                for await progress in await uploadTask.progress {
                    self.viewProgress = .uploadS3(progress.fractionCompleted)
                    self.regions[index].progress = self.viewProgress?.getProgress()

                    // fraction of upload as we scale upload to progress bar from 10 to 99%
                    if progress.fractionCompleted >= 1.0 {
                        let value = try await uploadTask.value
                        logger.info("Upload complete, value: \(value)")
                        fileUrl.stopAccessingSecurityScopedResource()
                        self.onUploadComplete(key: scanKey, path: value, index: index)
                    }
                }`

**Comment by jcjimenez** [comment] 2023-03-09 21:09
Hi, we have work in progress to make this better but it has taken longer than I anticipated. However, here is a workaround you can use to speed things up:

1. Download [PresignedUrlGenerator](https://gist.github.com/jcjimenez/add7b123514dd0360c88fb4072bc66ab) somewhere into your application/library. This performs the subset of the work used by Amplify in order to prepare for upload.
3. Use by entering something like the example below:
```
let generator = PresignedUrlGenerator(
    region: "us-east-1",
    bucket: mys3BucketName
)
let url = try await generator.presignedURL(
    for: myKey,
    accessLevel: .private
)
var request = URLRequest(url: url)
request.httpMethod = "PUT"
let task = session.uploadTask(with: request,
                              fromFile: fileURL)
task.delegate = self
task.resume()
```

You are likely using `amplifyconfig.json` in your application, and if that is the case, you should be able to get the relevant region and bucket by doing something like the following:

1. Download [AmplifyConfig](https://gist.github.com/jcjimenez/36462b984b4dbf40378b56a2b77f14a3) somewhere into your application/library.
2. Read your amplifyconfig.json file with something like:
```
let amplifyConfig = try AmplifyConfig.load(from: .main)
let generator = PresignedUrlGenerator(
    region: amplifyConfig.storage.plugins.awsS3StoragePlugin.region,
    bucket: amplifyConfig.storage.plugins.awsS3StoragePlugin.bucket
)

```

**Comment by zachrattner** [comment] 2023-03-10 01:05
Thank you @jcjimenez - do you know if this supports multipart POST uploads? Would it work for 50-100MB uploads?

**Comment by ruisebas** [comment] 2023-03-10 18:49
@zachrattner the provided [PresignedUrlGenerator](https://gist.github.com/jcjimenez/add7b123514dd0360c88fb4072bc66ab)  only supports the `PutObject` API, but it should be more than enough for 50-100MB uploads as the API [supports up to 5 GB](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html).

**Comment by jcjimenez** [comment] 2023-03-10 20:44
@zachrattner I hope this workaround did the trick! For reference, it is subject to the limits posted here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html

**Comment by babinowich** [comment] 2023-03-29 17:40
@jcjimenez thank you for the code, it worked for @zachrattner and i in that we now see quicker and more reliable responses regarding progress.

**Closed** 2023-05-03 13:10 UTC
Labels: bug, storage, follow up, slow-transfer

**Comment by alionthego** [comment] 2023-08-31 04:59
@atierian  Hi there, are you guys just fixing upload speeds or also looking at download speeds?  I'm using the amplify-swift version 2.0.0.  I have a client app in Tokyo and server US-EAST-1.  a file of 300mb will take over one hour to download from s3 bucket using:
`let downloadTask = Amplify.Storage.downloadFile(
            key: "myKey",
            local: downloadToFileName,
            options: nil
  )`
