### ISSUE TITLE
Session `isLoggedIn` becomes false after update from amplify-swift 1.7.2 -> 2.9.0

### ISSUE THREAD

**Issue by dakrawczyk** [aws-amplify/amplify-swift#2945] opened 2023-05-10 20:06 UTC
### Describe the bug

Hello, 

We recently updated our amplify from a **cocoapod** (1.7.2) to **swift package manager** (2.9.0)

It appears that this is resulting in our users being logged out of the application upon upgrade of the app. 

Our implementation follows the [suggested approach](https://amplify-ios-workshop.go-aws.com/30_add_authentication/20_client_code.html) but the `session.isSignedIn` is always returning false after the upgrade, despite the user being authenticated before the upgrade. 

On subsequent app launches, this `session.isSignedIn` is returning the value appropriately. It's only on the launch directly after the upgrade. 

We have reproduced this bug in an isolated environment, and it happens consistently when upgrading from 1.7.2 -> 2.9.0. I am happy to provide the sample project in both configuration (1.7.2 and 2.9.0) if it's helpful. 

I am not seeing anything about this in the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/ios/) so I'm hoping I can find some guidance here about the issue, or if perhaps there was a different approach that should be implemented. 

Thanks!

### Steps To Reproduce

```swift
1. Sign up with user on amplify 1.7.2
2. Sign in with user
3. Check sign in status -> (true)
4. Kill app
5. Reopen app (still on 1.7.2)
6. Check sign in status -> (true)
7. Upgrade to amplify 2.9.0
8. Check sign in status -> (false)
9. Sign in with user from above
10. Check sign in status -> (true)
```

### Expected behavior

We would expect that the Amplify SDK would retain the user's authentication status across SDK upgrades. 

### Amplify Framework Version

1.7.2 -> 2.9.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

NA

### Xcode version

14.2 (14C18)

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

Reproduced on iPhone 13 Pro

### iOS Version

Reproduced on iOS 16.0.2 

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by harsh62** [comment] 2023-05-10 20:11
@dakrawczyk 
Thanks for creating the issue. Would you be able to provide the following 2 things: 

1. `amplifyconfiguration.json` redacted all the sensitive information. 
2. Verbose logs when you are launching the app after signing in. Verbose logging can be enabled with `Amplify.Logging.logLevel = .verbose` before the plugin is configured. 

I will also try to reproduce this issue in my local environment and post an update.

**Comment by dakrawczyk** [comment] 2023-05-10 20:38
@harsh62 thanks for the quick reply. Let me know if you need anything more: 

[amplify_verbose_log.log](https://github.com/aws-amplify/amplify-swift/files/11445768/amplify_verbose_log.log)

[amplifyconfiguration_redacted.txt](https://github.com/aws-amplify/amplify-swift/files/11445778/amplifyconfiguration_redacted.txt)
(text file as `json` is not supported by github files)

**Comment by dakrawczyk** [comment] 2023-05-11 11:43
One more finding we just discovered- 

If you don't delete the build with 2.9.0, downgrade to 1.7.2, then upgrade 2.9.0 again the user remains logged in as expected. 

Perhaps this correlates to the keychain errors in the verbose logging above

**Comment by harsh62** [comment] 2023-05-16 02:47
@dakrawczyk I was able to repro and find the root cause of the issue. Would you be able to test the fix I have proposed in the linked PR. ([branch with the fix](https://github.com/aws-amplify/amplify-swift/tree/2945.fixing-migration-logic))

**Comment by dakrawczyk** [comment] 2023-05-16 14:59
@harsh62 definitely, any tips for integrating your branch? I assume SPM is out of the question. Download as a zip and reference the package directly?

**Comment by harsh62** [comment] 2023-05-16 15:56
@dakrawczyk 

You can actually use a custom branch as provided in the screenshot below. 
<img width="844" alt="Screenshot 2023-05-16 at 11 46 54 AM" src="https://github.com/aws-amplify/amplify-swift/assets/6162866/34885fff-c268-4fc0-b01d-70e2892a7767">

Or if you are using a `Package.swift`, use [package(url:branch:)](https://developer.apple.com/documentation/packagedescription/package/dependency/package(url:branch:))
```
.package(url: "https://github.com/aws-amplify/amplify-swift.git", branch: "2945.fixing-migration-logic"),
```

**Comment by dakrawczyk** [comment] 2023-05-16 16:45
@harsh62 that appears to have resolved the issue.

After logging in with 1.7.2, then upgrading to your branch (`2945.fixing-migration-logic`), the `session.isSignedIn` returns `true` appropriately.

Verbose logging here -- 
[verbose_logging_resolved.log](https://github.com/aws-amplify/amplify-swift/files/11490125/verbose_logging_resolved.log)

**Comment by harsh62** [comment] 2023-05-16 16:47
@dakrawczyk Thanks for confirming the resolution. We will prioritize to release this bug fix and will update the issue once its done. Appreciate the patience.

**Comment by dakrawczyk** [comment] 2023-05-16 16:50
@harsh62 thank you for the help. Do you have an estimate of when this fix would be available in production?

**Comment by atierian** [comment] 2023-05-17 20:14
Hey @dakrawczyk just wanted to let you know that this fix was included in [Amplify Swift 2.11.1](https://github.com/aws-amplify/amplify-swift/releases/tag/2.11.1).

Thanks for your patience and for reporting this issue!

**Comment by dakrawczyk** [comment] 2023-05-18 18:16
@atierian @harsh62 It appears that after installing the new SDK (2.11.1) onto a device, the SDK without the fix (2.9) is unusable on the device, even after deleting the app (most likely due to keychain not being cleared) 

Below is the error we receive with attempting to Sign in, and we receive a similar error on Sign up. 

```
Sign in failed AuthError: Unexpected error occurred with message: 
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-swift/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't.
Caused by:
KeychainStoreError: Keychain error occurred with status: -25299
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/davekrawczyk/Library/Developer/Xcode/DerivedData/MyAmplifyApp-dteqmydibqsubkbbjczgmcovlhwu/SourcePackages/checkouts/amplify-swift/AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStoreError.swift
function: recoverySuggestion
line: 69
```


I am unsure if this is a flow amplify is required to account for, but it's a common requirement for our team to test upgrades and we're often installing old versions to verify functionality.

**Comment by harsh62** [comment] 2023-05-18 18:38
@dakrawczyk Thank you for coming back to us and pointing out the issue after the update happened. Our team is actively investigating the issue and working towards a fix. We will post an update soon. 

As a matter of precaution, Amplify has removed version 2.11.1 from the releases and will be rolling back the keychain change in 2.11.2 in the next few minutes.

**Comment by dakrawczyk** [comment] 2023-05-18 20:04
@harsh62 will running [2.11.2](https://github.com/aws-amplify/amplify-swift/releases/tag/2.11.2) revert the change in our device keychains and make them usable again with 2.9?

**Comment by harsh62** [comment] 2023-05-19 15:25
@dakrawczyk We believe that we have correctly fixed the migration issue. Would you be able to validate if this is not causing any problems or regressions in your test environment? The branch name is `keychain-setting-issue`.

**Comment by dakrawczyk** [comment] 2023-05-19 18:33
@harsh62 it appears that this does not cause the keychain corruption issue that 2.11.1 did. 

If possible, please expedite this fix for us. 

My testing flow below: 

### Test flow for users who have upgraded to 2.9 and were logged out
(1.7) log in, success
(1.7) -> (2.9) Logged out (expected)
(2.9) Log in, success
**(2.9) -> (keychain-setting-issue)  still logged in :white_check_mark:**


### Test flow for users that have not upgraded
(1.7) login success
**(1.7) -> (keychain-setting-issue) still logged in :white_check_mark:**


### Test flow that resulted in our blocked devices
(1.7) log in, success
(1.7) -> (2.9) Logged out (expected)
(2.9) Log in, success
(2.9) -> (keychain-setting-issue)  still logged in
(delete app)
(1.7) log in, success
(1.7) -> (2.9) Logged out (expected)
**(2.9) Log in, success :white_check_mark: (previous fix 2.11.1 failed with keychain issue)**

**Comment by harsh62** [comment] 2023-05-19 18:36
@dakrawczyk Thanks for your detailed analysis and glad the issue is resolved. I will work with my team to get this released early next week.

**Comment by ethan021021** [comment] 2023-05-26 17:41
Is this the expected behavior on 2.11.4?

1. Sign into app with SDK version 2.11.4
2. Delete app from device
3. Reinstall app with SDK version 2.11.4
4. User is still logged in or `authSession.isSignedIn == true`?

**Comment by harsh62** [comment] 2023-05-26 17:57
> Is this the expected behavior on 2.11.4?
> 
> 1. Sign into app with SDK version 2.11.4
> 2. Delete app from device
> 3. Reinstall app with SDK version 2.11.4
> 4. User is still logged in or `authSession.isSignedIn == true`?

Hey @ethan021021 .. Yes this is expected. Amplify stores session data in the keychain which is persisted on the devices across app deletions and reinstalls. 

This has been the behaviour since Amplify V1.

**Comment by ethan021021** [comment] 2023-05-26 17:59
> > Is this the expected behavior on 2.11.4?
> > 
> > 1. Sign into app with SDK version 2.11.4
> > 2. Delete app from device
> > 3. Reinstall app with SDK version 2.11.4
> > 4. User is still logged in or `authSession.isSignedIn == true`?
> 
> Hey @ethan021021 .. Yes this is expected. Amplify stores session data in the keychain which is persisted on the devices across app deletions and reinstalls.
> 
> This has been the behaviour since Amplify V1.

Sadly this is not the behavior I'm seeing dating even back to the Amplify 2.10.0 SDK

After deleting the app on Simulator/Device `authSession.isSignedIn == false`

**Comment by harsh62** [comment] 2023-05-26 19:10
> Sadly this is not the behavior I'm seeing dating even back to the Amplify 2.10.0 SDK
> 
> After deleting the app on Simulator/Device authSession.isSignedIn == false

@ethan021021  I am extremely sorry to provide incorrect information earlier.

Amplify V2 actually removes the previous session, after the app is reinstalled and launched. So after a app reinstall, `isSignedIn` will be `false`.

But Amplify V1 is the opposite, where app session data is preserved across reinstallations.

**Comment by ethan021021** [comment] 2023-05-26 19:14
> > Sadly this is not the behavior I'm seeing dating even back to the Amplify 2.10.0 SDK
> > After deleting the app on Simulator/Device authSession.isSignedIn == false
> 
> @ethan021021 I am extremely sorry to provide incorrect information earlier.
> 
> Amplify V2 actually removes the previous session, after the app is reinstalled and launched. So after a app reinstall, `isSignedIn` will be `false`.
> 
> But Amplify V1 is the opposite, where app session data is preserved across reinstallations.

No worries! It happens :) 

I'm a bit confused though on why this behavior was changed? We upgraded recently to V2 and sadly can't downgrade back to V1 (as the migration to V2 was pretty scope heavy). We depend pretty highly on the behavior of Amplify V1 and how the auth session is stored in the keychain and how it persists through reinstalls/updates/etc. Are there any plans to add this functionality back to V2? Maybe a boolean value on Amplify Auth plugin initialization could control whether the auth session should persist through reinstalls, etc

**Comment by harsh62** [comment] 2023-05-26 19:30
@ethan021021 This behaviour was changed because of a [feature request](https://github.com/aws-amplify/amplify-swift/issues/1314) that the team worked on as part of Amplify V2. 

Could you please open a new issue with your requirements to track it as a feature request? And meanwhile I can work with my team to come up with a work around for you. A new issue would also help other people looking for a similar solution as yours. 

Thanks for your comments. We are committed to provide a solution for you.

**Comment by ethan021021** [comment] 2023-05-26 19:49
> @ethan021021 This behaviour was changed because of a [feature request](https://github.com/aws-amplify/amplify-swift/issues/1314) that the team worked on as part of Amplify V2.
> 
> Could you please open a new issue with your requirements to track it as a feature request? And meanwhile I can work with my team to come up with a work around for you. A new issue would also help other people looking for a similar solution as yours.
> 
> Thanks for your comments. We are committed to provide a solution for you.

Opened! #2995

**Comment by harsh62** [comment] 2023-06-02 23:11
Closing the issue.

**Closed by harsh62** 2023-06-02 23:11 UTC
Labels: bug, auth, closing soon
