### ISSUE TITLE
Unexpected error occurred with message: Could not retreive AWS credentials, credential value is nil or empty. #2527

### ISSUE THREAD

**Issue by michaeljajou** [aws-amplify/amplify-swift#2565] opened 2022-11-11 22:31 UTC
### Describe the bug

This is referencing the same bug listed here:

https://github.com/aws-amplify/amplify-swift/issues/2527 

After releasing the update with the most up to date version of Amplify - it seems our effected users are still experiencing this issue. For reference - this is our Podfile.lock - please let me know if I am on an outdated/incorrect version. 

```
PODS:
  - Amplify (1.28.2):
    - Amplify/Default (= 1.28.2)
  - Amplify/Default (1.28.2)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.28.2):
    - AWSAuthCore (~> 2.28.0)
    - AWSCognitoIdentityProvider (~> 2.28.0)
    - AWSCognitoIdentityProviderASF (~> 2.28.0)
    - AWSCore (~> 2.28.0)
    - AWSMobileClient (~> 2.28.0)
    - AWSPluginsCore (= 1.28.2)
  - AWSAuthCore (2.28.3):
    - AWSCore (= 2.28.3)
  - AWSCognitoIdentityProvider (2.28.3):
    - AWSCognitoIdentityProviderASF (= 2.28.3)
    - AWSCore (= 2.28.3)
  - AWSCognitoIdentityProviderASF (2.28.3):
    - AWSCore (= 2.28.3)
  - AWSCore (2.28.3)
  - AWSMobileClient (2.28.3):
    - AWSAuthCore (= 2.28.3)
    - AWSCognitoIdentityProvider (= 2.28.3)
    - AWSCognitoIdentityProviderASF (= 2.28.3)
    - AWSCore (= 2.28.3)
  - AWSPluginsCore (1.28.2):
    - Amplify (= 1.28.2)
    - AWSCore (~> 2.28.0)
  - mamba (2.2.1)
  - SwiftCheck (0.12.0)
  - SwiftLint (0.49.1)
  - SwiftUIPager (2.5.0)
```

### Steps To Reproduce

```swift
As mentioned 
https://github.com/aws-amplify/amplify-swift/issues/2527
```

### Expected behavior

As mentioned 
https://github.com/aws-amplify/amplify-swift/issues/2527 

### Amplify Framework Version

1.28.2

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

4.41.2

### Xcode version

14

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Device

iPhone 14 

### iOS Version

iOS 16

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by atierian** [comment] 2022-11-14 21:59
Hey @michaeljajou, thanks for opening this new issue.
I see in the original issue you mentioned:
>  but I have a feeling they haven't updated, waiting for a confirmation from them.

Are you able to confirm that your user has indeed updated to your new app version? The versions included in your podfile contain the fix. So if you're still experiencing it, it may be related to something else. Have you been able to reproduce this issue yourself? We were able to reproduce the issue based on the previous version, but I have not been able to reproduce it with the updated versions you're using.

**Comment by michaeljajou** [comment] 2022-11-15 20:39
@atierian Yes - it I confirmed the user updated the app to the latest version which contains the version of Amplify as mentioned above. 

I haven't been able to reproduce the issue - the only information I am aware of is that after the user purchased a new phone, they restored their iPhone from an iCloud backup - and when they went to go sign into the application, the error reads "An unexpected error has occurred."

The user is not able to login nor create a new account - and deleting/redownloading the app doesn't seem to help

**Comment by atierian** [comment] 2022-11-15 21:44
Ok, it sounds like the backup may have carried over some keychain items and the app is in an inconsistent state.
There were some changes around keychain items and device backups in the AWS SDK for iOS recently; I'm looking into this.

Do you know which version of Amplify (and AWS SDK for iOS) was used in your app version this user had before they purchased a new phone and updated? If we know that, we can take those exact steps to try to reproduce the issue, and will likely be able to resolve this more quickly for your user.

**Comment by michaeljajou** [comment] 2022-11-15 21:49
Sure - here is some information regarding that, let me know if this helps:

- iPhone 11,8
- iOS 15.6.1

```
PODS:
  - Amplify (1.28.1):
    - Amplify/Default (= 1.28.1)
  - Amplify/Default (1.28.1)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.28.1):
    - AWSAuthCore (~> 2.28.0)
    - AWSCognitoIdentityProvider (~> 2.28.0)
    - AWSCognitoIdentityProviderASF (~> 2.28.0)
    - AWSCore (~> 2.28.0)
    - AWSMobileClient (~> 2.28.0)
    - AWSPluginsCore (= 1.28.1)
  - AWSAuthCore (2.28.0):
    - AWSCore (= 2.28.0)
  - AWSCognitoIdentityProvider (2.28.0):
    - AWSCognitoIdentityProviderASF (= 2.28.0)
    - AWSCore (= 2.28.0)
  - AWSCognitoIdentityProviderASF (2.28.0):
    - AWSCore (= 2.28.0)
  - AWSCore (2.28.0)
  - AWSMobileClient (2.28.0):
    - AWSAuthCore (= 2.28.0)
    - AWSCognitoIdentityProvider (= 2.28.0)
    - AWSCognitoIdentityProviderASF (= 2.28.0)
    - AWSCore (= 2.28.0)
  - AWSPluginsCore (1.28.1):
    - Amplify (= 1.28.1)
    - AWSCore (~> 2.28.0)
  - mamba (2.2.1)
  - SwiftCheck (0.12.0)
  - SwiftLint (0.49.1)
  - SwiftUIPager (2.5.0)

DEPENDENCIES:
  - Amplify
  - AmplifyPlugins/AWSCognitoAuthPlugin
  - mamba
  - SwiftCheck
  - SwiftLint
  - SwiftUIPager

SPEC REPOS:
  trunk:
    - Amplify
    - AmplifyPlugins
    - AWSAuthCore
    - AWSCognitoIdentityProvider
    - AWSCognitoIdentityProviderASF
    - AWSCore
    - AWSMobileClient
    - AWSPluginsCore
    - mamba
    - SwiftCheck
    - SwiftLint
    - SwiftUIPager

SPEC CHECKSUMS:
  Amplify: 050d2daf2c5754eab171606fa3e35619c4babf6e
  AmplifyPlugins: 55b7fe0fe9a4788b0602b9e65601a832b814a96a
  AWSAuthCore: 658c331fe5cbc58608ced499aa0d8d46c57e9c96
  AWSCognitoIdentityProvider: 9778edc430206a1bf67ff5f0c7a7b130fa4a5380
  AWSCognitoIdentityProviderASF: a82f81ad75fce6d8c826ed394fa3cf7c51306897
  AWSCore: 0ebe9ba8a459893cdf268ce0bae61875efd0182b
  AWSMobileClient: 8d466f135e8d851a76e57cbfe65bb67eb522b64c
  AWSPluginsCore: a12e315533b041485d722bdb394bf150ad9cc78e
  mamba: dae7476d3dc81ec9fea7784b3006e004133dc48e
  SwiftCheck: d1dd04d955cc76620b0f84e087536bd059a11c24
  SwiftLint: 32ee33ded0636d0905ef6911b2b67bbaeeedafa5
  SwiftUIPager: b314d8923bef0bde743c904bb74fcc7a05fd3422

PODFILE CHECKSUM: 73be5953890e542753060c1ab3d817759799bf4d

COCOAPODS: 1.11.2
```

**Comment by atierian** [comment] 2022-11-15 22:04
These are the same versions you mentioned [here](https://github.com/aws-amplify/amplify-swift/issues/2527#issuecomment-1303599941).

Just to be certain, the user was using your app with these Amplify / AWS SDK for iOS versions before they changed phones **and** the same versions after they changed phones? This may be a long shot, but do you happen to know if this particular user ever used a version of your app that uses other versions of Amplify / AWS SDK for iOS?

I appreciate your patience while we're actively investigating this.

**Comment by michaeljajou** [comment] 2022-11-19 23:43
@atierian apologize for the delay - looks like the user first created an account Apr 29, 2022, would that help? At that time, here was the pods:

```
  - Amplify (1.23.0):
    - Amplify/Default (= 1.23.0)
  - Amplify/Default (1.23.0)
  - AmplifyPlugins/AWSAPIPlugin (1.23.0):
    - AppSyncRealTimeClient (~> 1.8)
    - AWSCore (~> 2.27.0)
    - AWSPluginsCore (= 1.23.0)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.23.0):
    - AWSAuthCore (~> 2.27.0)
    - AWSCognitoIdentityProvider (~> 2.27.0)
    - AWSCognitoIdentityProviderASF (~> 2.27.0)
    - AWSCore (~> 2.27.0)
    - AWSMobileClient (~> 2.27.0)
    - AWSPluginsCore (= 1.23.0)
```

**Comment by michaeljajou** [comment] 2022-12-23 01:55
@atierian any update on this issue? Just received the same issue from another user after they purchased a new phone and restored from iCloud backup.

**Comment by okharajpoot** [comment] 2022-12-27 21:05
UnknownException: Unable to get valid sign in session from the end user
The same issue appears on iPhone, amplify version is 0.6.10

**Comment by edgillett** [comment] 2022-12-28 15:32
Same issues here - must have had over 50+ different complaints from users - exactly the same issue - restore of the app after a new phone purchased. What can we do to workaround this short of asking them to do a phone reset and clean install the app (which is terrible, obviously)

**Comment by ameter** [comment] 2022-12-28 16:51
@michaeljajou @okharajpoot @edgillett Thanks for reporting and following up with additional information.  We are working to reproduce this issue and identify the root cause.

In the meantime, a potential work-around would be to detect this state by checking to if both Auth.getCurrentUser() == nil and Auth.fetchAuthSession() -> isLoggedIn == true and then call Amplify.Auth.signOut() to return to a proper signed out state.

**Comment by royjit** [comment] 2022-12-28 19:52
@okharajpoot @edgillett will you be able to provide us the verbose logs related to this issue. It will be helpful to debug the issue further. You can enable verbose logs by:

```
import AWSCore

        AWSDDLog.sharedInstance.add(AWSDDTTYLogger())
        AWSDDLog.sharedInstance.logLevel = .verbose
```

If you do not have the exact logs when the issue happened, you can send us logs from the code path where you suspect this issue happened. 

Make sure to redact any sensitive information before sending logs: [Logs Guidance](https://github.com/aws-amplify/aws-sdk-ios/blob/main/LogsGuidance.md)

**Comment by royjit** [comment] 2022-12-28 20:27
> UnknownException: Unable to get valid sign in session from the end user The same issue appears on iPhone, amplify version is 0.6.10

@okharajpoot 
Are you also facing this issue when the customer migrate to a new iPhone? You seems to be using Flutter app by looking at the version number, the particular error you mentioned is typically thrown when session expired. Where you able to signIn the user back when this error occurred? 
Also what is the result of `Amplify.Auth.fetchAuthsession` when this issue happened?

**Comment by okharajpoot** [comment] 2022-12-29 09:52
> Logs Guidance

it is not going to work as Auth.getCurrentUser() == nil is never true in our case.

**Comment by ameter** [comment] 2022-12-30 18:40
@michaeljajou @okharajpoot @edgillett We just released a fix that we expect will address this issue.  The fix is included in amplify-swift v1.28.4.  Please try this version and let us know if it solves the problem.

**Comment by atierian** [comment] 2023-01-09 19:20
@michaeljajou @okharajpoot @edgillett 
Do you have any updates on whether the fix included in v1.28.4 resolves your issue?

**Comment by edgillett** [comment] 2023-01-09 20:34
Yes! Sorry for the late reply. It's resolved our issue, across our
installed customer base who were experiencing the issues. Thank you.

**Comment by atierian** [comment] 2023-01-09 21:17
That's great news, thanks for letting us know!
@michaeljajou since you opened this issue, we'd love to get confirmation from you as well before closing this. Please let us know when you get a chance.

**Comment by atierian** [comment] 2023-01-20 18:26
Closing as we believe this issue to now be resolved. If anyone is experiencing this on v1.28.4 or later, please comment here and/or open another issue. Thanks!

**Closed by atierian** 2023-01-20 18:26 UTC
Labels: bug, auth
