### ISSUE TITLE
DataStore Bug please resolve

### ISSUE THREAD

**Issue by jaymeen-unadkat-differenz** [aws-amplify/amplify-swift#3502] opened 2024-02-07 12:56 UTC
### Describe the bug

Facing this issue in iOS

onUpdateValueListener: data(Swift.Result<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>, Amplify.GraphQLResponseError<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>>>.success(AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>(model: AWSPluginsCore.AnyModel(id: "\"DRI#2\"#\"DRI#2\"", instance: ImbybeTestDemo.Imbybe(pk: "DRI#2", sk: "DRI#2", gsi1: Optional("master"), gsisk1: Optional("DRI#2"), name: Optional("Drink 121"), description: Optional("drink desc 2"), imageURL: Optional([]), ordersEmail: nil, type: Optional("COCKTAIL"), street: nil, city: nil, state: nil, zipCode: nil, productCost: nil, productCategory: nil, numberOfDrinks: Optional(60), publishDate: nil, expirationDate: nil, eligibleZipCodes: Optional([]), numberOfCampaigns: nil, numberOfOffers: nil, remainingNumberOfCampaigns: nil, productQuantity: nil, primaryProduct: Optional(false), lat: nil, lng: nil, operatingHours: nil, cognitoID: nil, startingNumberOfOffers: nil, remainingNumberOfOffers: nil, campaignStatus: nil, rating: nil, comment: nil, createdAt: Optional(Amplify.Temporal.DateTime(foundationDate: 2024-02-07 10:41:15 +0000, timeZone: Optional(GMT (fixed)))), updatedAt: Optional(Amplify.Temporal.DateTime(foundationDate: 2024-02-07 12:31:09 +0000, timeZone: Optional(GMT (fixed))))), modelName: "Imbybe"), syncMetadata: AWSPluginsCore.MutationSyncMetadata(id: "Imbybe|\"DRI#2\"#\"DRI#2\"", deleted: false, lastChangedAt: 1707309069243, version: 7))))
receive(_:): data(Swift.Result<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>, Amplify.GraphQLResponseError<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>>>.success(AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>(model: AWSPluginsCore.AnyModel(id: "\"DRI#2\"#\"DRI#2\"", instance: ImbybeTestDemo.Imbybe(pk: "DRI#2", sk: "DRI#2", gsi1: Optional("master"), gsisk1: Optional("DRI#2"), name: Optional("Drink 121"), description: Optional("drink desc 2"), imageURL: Optional(", ordersEmail: nil, type: Optional("COCKTAIL"), street: nil, city: nil, state: nil, zipCode: nil, productCost: nil, productCategory: nil, numberOfDrinks: Optional(60), publishDate: nil, expirationDate: nil, eligibleZipCodes: Optional([]), numberOfCampaigns: nil, numberOfOffers: nil, remainingNumberOfCampaigns: nil, productQuantity: nil, primaryProduct: Optional(false), lat: nil, lng: nil, operatingHours: nil, cognitoID: nil, startingNumberOfOffers: nil, remainingNumberOfOffers: nil, campaignStatus: nil, rating: nil, comment: nil, createdAt: Optional(Amplify.Temporal.DateTime(foundationDate: 2024-02-07 10:41:15 +0000, timeZone: Optional(GMT (fixed)))), updatedAt: Optional(Amplify.Temporal.DateTime(foundationDate: 2024-02-07 12:31:09 +0000, timeZone: Optional(GMT (fixed))))), modelName: "Imbybe"), syncMetadata: AWSPluginsCore.MutationSyncMetadata(id: "Imbybe|\"DRI#2\"#\"DRI#2\"", deleted: false, lastChangedAt: 1707309069243, version: 7))))
dispose(of subscriptionEvent): data(Swift.Result<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>, Amplify.GraphQLResponseError<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>>>.success(AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>(model: AWSPluginsCore.AnyModel(id: "\"DRI#2\"#\"DRI#2\"", instance: ImbybeTestDemo.Imbybe(pk: "DRI#2", sk: "DRI#2", gsi1: Optional("master"), gsisk1: Optional("DRI#2"), name: Optional("Drink 121"), description: Optional("drink desc 2"), imageURL: Optional([]), ordersEmail: nil, type: Optional("COCKTAIL"), street: nil, city: nil, state: nil, zipCode: nil, productCost: nil, productCategory: nil, numberOfDrinks: Optional(60), publishDate: nil, expirationDate: nil, eligibleZipCodes: Optional([]), numberOfCampaigns: nil, numberOfOffers: nil, remainingNumberOfCampaigns: nil, productQuantity: nil, primaryProd

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to 'Amplify Console'
2. Click on 'Content -> Data Manager'
3. Update any value in the model
4. See the error in the XCode console
```

### Expected behavior

Data should update properly

### Amplify Framework Version

2.25.6

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

12.10.1

### Xcode version

XCode 15

### Is this a regression?

Yes

### OS Version

14.0

### Device

Simulator iPhone 11

### Specific to simulators

No - Not working anywhere

### Additional context

Working correctly on Android

**Comment by lawmicha** [comment] 2024-02-07 14:20
Hi @jaymeen-unadkat-differenz, thanks for opening the issue, here's the formatted error

```
onUpdateValueListener: data(
    Swift.Result<
        AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>,
        Amplify.GraphQLResponseError<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>>
    >.success(
        AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>(
            model: AWSPluginsCore.AnyModel(
                id: ""DRI#2"#"DRI#2"",
                instance: ImbybeTestDemo.Imbybe(
                    pk: "DRI#2",
                    sk: "DRI#2",
                    gsi1: Optional("master"),
                    gsisk1: Optional("DRI#2"),
                    name: Optional("Drink 121"),
                    description: Optional("drink desc 2"),
                    imageURL: Optional([]),
                    ordersEmail: nil,
                    type: Optional("COCKTAIL"),
                    street: nil,
                    city: nil,
                    state: nil,
                    zipCode: nil,
                    productCost: nil,
                    productCategory: nil,
                    numberOfDrinks: Optional(60),
                    publishDate: nil,
                    expirationDate: nil,
                    eligibleZipCodes: Optional([]),
                    numberOfCampaigns: nil,
                    numberOfOffers: nil,
                    remainingNumberOfCampaigns: nil,
                    productQuantity: nil,
                    primaryProduct: Optional(false),
                    lat: nil,
                    lng: nil,
                    operatingHours: nil,
                    cognitoID: nil,
                    startingNumberOfOffers: nil,
                    remainingNumberOfOffers: nil,
                    campaignStatus: nil,
                    rating: nil,
                    comment: nil,
                    createdAt: Optional(
                        Amplify.Temporal.DateTime(
                            foundationDate: 2024-02-07 10:41:15 +0000,
                            timeZone: Optional(GMT (fixed))
                        )
                    ),
                    updatedAt: Optional(
                        Amplify.Temporal.DateTime(
                            foundationDate: 2024-02-07 12:31:09 +0000,
                            timeZone: Optional(GMT (fixed))
                        )
                    )
                ),
                modelName: "Imbybe"
            ),
            syncMetadata: AWSPluginsCore.MutationSyncMetadata(
                id: "Imbybe|"DRI#2"#"DRI#2"",
                deleted: false,
                lastChangedAt: 1707309069243,
                version: 7
            )
        )
    )
)

receive(_:): data(
    Swift.Result<
        AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>,
        Amplify.GraphQLResponseError<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>>
    >.success(
        AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>(
            model: AWSPluginsCore.AnyModel(
                id: ""DRI#2"#"DRI#2"",
                instance: ImbybeTestDemo.Imbybe(
                    pk: "DRI#2",
                    sk: "DRI#2",
                    gsi1: Optional("master"),
                    gsisk1: Optional("DRI#2"),
                    name: Optional("Drink 121"),
                    description: Optional("drink desc 2"),
                    imageURL: Optional([]),
                    ordersEmail: nil,
                    type: Optional("COCKTAIL"),
                    street: nil,
                    city: nil,
                    state: nil,
                    zipCode: nil,
                    productCost: nil,
                    productCategory: nil,
                    numberOfDrinks: Optional(60),
                    publishDate: nil,
                    expirationDate: nil,
                    eligibleZipCodes: Optional([]),
                    numberOfCampaigns: nil,
                    numberOfOffers: nil,
                    remainingNumberOfCampaigns: nil,
                    productQuantity: nil,
                    primaryProduct: Optional(false),
                    lat: nil,
                    lng: nil,
                    operatingHours: nil,
                    cognitoID: nil,
                    startingNumberOfOffers: nil,
                    remainingNumberOfOffers: nil,
                    campaignStatus: nil,
                    rating: nil,
                    comment: nil,
                    createdAt: Optional(
                        Amplify.Temporal.DateTime(
                            foundationDate: 2024-02-07 10:41:15 +0000,
                            timeZone: Optional(GMT (fixed))
                        )
                    ),
                    updatedAt: Optional(
                        Amplify.Temporal.DateTime(
                            foundationDate: 2024-02-07 12:31:09 +0000,
                            timeZone: Optional(GMT (fixed))
                        )
                    )
                ),
                modelName: "Imbybe"
            ),
            syncMetadata: AWSPluginsCore.MutationSyncMetadata(
                id: "Imbybe|"DRI#2"#"DRI#2"",
                deleted: false,
                lastChangedAt: 1707309069243,
                version: 7
            )
        )
    )
)

dispose(of subscriptionEvent): data(
    Swift.Result<
        AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>,
        Amplify.GraphQLResponseError<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>>
    >.success(
        AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>(
            model: AWSPluginsCore.AnyModel(
                id: ""DRI#2"#"DRI#2"",
                instance: ImbybeTestDemo.Imbybe(
                    pk: "DRI#2",
                    sk: "DRI#2",
                    gsi1: Optional("master"),
                    gsisk1: Optional("DRI#2"),
                    name: Optional("Drink 121"),
                    description: Optional("drink desc 2"),
                    imageURL: Optional([]),
                    ordersEmail: nil,
                    type: Optional("COCKTAIL"),
                    street: nil,
                    city: nil,
                    state: nil,
                    zipCode: nil,
                    productCost: nil,
                    productCategory: nil,
                    numberOfDrinks: Optional(60),
                    publishDate: nil,
                    expirationDate: nil,
                    eligibleZipCodes: Optional([]),
                    numberOfCampaigns: nil,
                    numberOfOffers: nil,
                    remainingNumberOfCampaigns: nil,
                    productQuantity: nil,
                    primaryProd

```

Can you provide us with the schema of `Imbybe` and it's connected models if it has any, such as `belongsTo`/`hasMany` relationships?

You can see my other response in https://github.com/aws-amplify/amplify-swift/issues/3495 regarding Amplify Studio's usability with Amplify Swift. Amplify Swift requires lazy loading enabled for it to be compatible with the subscription events sourced from other platforms.

> In cli.json do you have the feature flag generateModelsForLazyLoadAndCustomSelectionSet set to true? If you are setting it to true now, please make sure to re-run amplify codegen models to re-generate the proper files

**Comment by lawmicha** [comment] 2024-02-08 13:52
duplicate of https://github.com/aws-amplify/amplify-swift/issues/3495

**Closed by lawmicha** 2024-02-08 13:52 UTC
Labels: bug, pending-response, datastore
