### ISSUE TITLE
Datastore fails to save model with empty but optional 1:n relation 

### ISSUE THREAD

**Issue by Erik7354** [aws-amplify/amplify-swift#1140] opened 2021-04-03 16:14 UTC
**Describe the bug**
When having two models connected over an optional bidirectional 1:n relation, traditionally a Post with many Comments, and then trying to save a Comment with nil as "post" and "postID" attributes, the save fails saying it expected a String.

**To Reproduce**
1. Set up an Amplify App with two Models connected over a bidirectional 1:n relation. To reproduce I used the following graphql schema fully generated by the AdminUI:
```
type Comment @model @auth(rules: [{allow: public}]) @key(name: "byPost", fields: ["postID"]) {
  id: ID!
  content: String
  postID: ID
  post: Post @connection
}

type Post @model @auth(rules: [{allow: public}]) {
  id: ID!
  title: String
  content: String
  comments: [Comment] @connection(keyName: "byPost", fields: ["id"])
}
```
2. Try to save a Comment without any connection to a Post:
```
Amplify.DataStore.save(Comment(
    content: "Lorem Ipsum"
)).sink(receiveCompletion: { completion in
    print("Completion: \(completion)")
}, receiveValue: { result in
    print("Result: \(result)")
})
```
3. The Console Output should be sth like this:
```
Completion: failure(DataStoreError: The data couldn’t be read because it is missing.
Recovery suggestion: The data couldn’t be read because it is missing.
Caused by:
valueNotFound(
  Swift.String, Swift.DecodingError.Context(codingPath: [
    CodingKeys(stringValue: "elements", intValue: nil), 
    _JSONKey(stringValue: "Index 0", intValue: 0), 
    CodingKeys(stringValue: "post", intValue: nil), 
    CodingKeys(stringValue: "id", intValue: nil)
  ], 
  debugDescription: "Expected String value but found null instead.", underlyingError: nil)
))
```

**Expected behavior**
It should save the Comment to the database without any connection to a Post (even if this wouldn't make much sense in this case).

**Screenshots**
The Model within the AdminUI.
<img width="1096" alt="Bildschirmfoto 2021-04-03 um 18 10 01" src="https://user-images.githubusercontent.com/31774332/113484305-dfcaef00-94a7-11eb-9f79-0a0d3d27a15b.png">

**Environment**
 - Amplify Framework Version: 1.7.2
 - Dependency Manager: Cocoapods
 - Swift Version: 5.0
 - AmplifyCLI Version: 4.46.1

**Device Information**
 - Device: iPad Pro Simulator
 - iOS Version: iOS 14.4

**Additional context**
The problem can be fixed by having a Post given to the Comment as "post" attribute. 
In case this is expected behavior and I missed sth in the documentation or elsewhere I apologize for the inconvenience but I would still think that the error given by Swift is not well suited for explaining the underlying issue.

**Comment by palpatim** [comment] 2021-04-05 16:21
@Erik7354

Thanks for reporting this. I believe the behavior you're seeing is expected, but as you identify, we should do a better job helping you recover. Even better, we should try to prevent this from happening in the first place. Bottom line is, a 1:1 relationship requires both sides of the relationship to be present upon saving. In your case, as you noted, you'll have to provide a value for the `post` field when you save your `Comment.

@aws-amplify/ios-team: I think we've got a couple of things to look at here:

**Conflicting requirements between schema and annotation**
1. The GraphQL schema defines `post` as an optional field on `Comment`
2. The `@connection` annotation for a 1:1 relationship would enforce that `post` must NOT be null. An optional `post` on the `Comment` type would be modeled as a 0-1:1 relationship, which I don't *think* we support. 

How can we resolve this ambiguity? Could codegen perform a validation and note that the `@connection` requires `post` to be a required type? Should we emit a warning about that? Could AdminUI generate the field as required rather than optional in the schema?

**Unclear documentation**
How can we clarify the documentation around relationship types? Is it extant, but not linked to the appropriate place? Should/can we link it in the AdminUI? Assuming codgen does validation, could we link to docs in the validation message?

**Unclear error**
In this case, the Swift error is technically accurate (our Swift GraphQL Document creation code inspected the 1:1 relationship and expected the `post` side of the relationship to be fulfilled with a String value containing the Post ID, but got a `nil` value instead), but not as helpful as we want. The "this should not happen" assertion is misleading in this case as well, since the current state of tooling allows for this to happen, and our code should be more resilient, or at least more helpful in determining the root cause.

We'll investigate this and make appropriate work items

**Comment by Erik7354** [comment] 2021-04-05 20:32
@palpatim 

Thanks for the reply. Let me know if you need any further information.

**Comment by diegocstn** [comment] 2021-10-18 23:00
@Erik7354 Thanks for reporting this. We’re working on ways to make DataStore relationships simpler. Once we get that done, we may need to adjust code in the DataStore plugin to properly handle the situation above. We’ll update this issue when we have more information.

**Comment by thisisabhash** [comment] 2023-05-09 05:43
Hello, 
Thank you for your patience and we apologize for the delay in response. This issue seems fixed in the latest CLI and Amplify releases. For context, I used Amplify version 2.9.0 and CLI version 11.0.3. With the new GraphQL v2 transformer, the schema would like below: 

```
type Comment @model 
@auth(rules: [{allow: public}]) {
  id: ID!
  content: String
  postID: ID @index(name: "byPost")
  post: Post @belongsTo(fields: ["postID"])
}

type Post @model 
@auth(rules: [{allow: public}]) {
  id: ID!
  title: String
  content: String
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
}
```

I used the below code snippet: 

```
func createPostAndComment() async {
    let comment = Comment(content: "Lorem Ipsum")
    do {
        let savedComment = try await Amplify.DataStore.save(comment)
        print("[GH1140]Saved comment: \(savedComment)")
    } catch (let error) {
        print("[GH1140]Error saving comment: \(error)")
    }
}
```

Here's a screenshot from the console log:

<img width="1582" alt="Screenshot 2023-05-08 at 10 42 14 PM" src="https://user-images.githubusercontent.com/23294582/237004460-10a7daf2-31ef-4286-bf25-29b58c8f167e.png">

Please let us know if you're still facing this problem.

**Comment by Erik7354** [comment] 2023-05-10 16:12
Hello,
thanks for the continues work on the problem. Within the last year we already migrated away from AWS Amplify. Nevertheless I spun up the old project and can confirm that the issue is now fixed.

**Closed** 2023-05-10 16:12 UTC
Labels: bug, datastore, closing soon, p2
