### ISSUE TITLE
MFA confirmation with Authenticator App is broken

### ISSUE THREAD

**Issue by rpatel8del** [aws-amplify/amplify-swift#2572] opened 2022-11-15 06:00 UTC
When I try to call sign in for a user that has MFA set on the Authenticator App, the call returns an AuthError, citing its an "UnSupported challenge response softwareTokenMfa"
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/102267573/201838175-ddba9f49-6bcb-422f-9fe8-d4233206db14.png)
Broken on the new v2.1.0 but works fine on the older v1.28.3.

**Comment by rpatel8del** [comment] 2022-11-16 00:32
Hey guys, is there an ETA on this bug?

**Comment by harsh62** [comment] 2022-11-16 03:06
@rpatel8del 

Can you share the code snippet that you are using for `softwareTokenMfa`. It seems that signing in software token MFA is not supported in 1.x and 2.x. If you are able to successfully confirm sign in with `softwareTokenMfa` in 1.28.3, I would like to understand how you are parsing the sign in response. Because ATM sign in only returns one of the following as next steps. 

```
public enum AuthSignInStep {

    /// Auth step is SMS multi factor authentication.
    ///
    /// Confirmation code for the MFA will be send to the provided SMS.
    case confirmSignInWithSMSMFACode(AuthCodeDeliveryDetails, AdditionalInfo?)

    /// Auth step is in a custom challenge depending on the plugin.
    ///
    case confirmSignInWithCustomChallenge(AdditionalInfo?)

    /// Auth step required the user to give a new password.
    ///
    case confirmSignInWithNewPassword(AdditionalInfo?)

    /// Auth step required the user to change their password.
    ///
    case resetPassword(AdditionalInfo?)

    /// Auth step that required the user to be confirmed
    ///
    case confirmSignUp(AdditionalInfo?)

    /// There is no next step and the signIn flow is complete
    ///
    case done
}
```

**Comment by rpatel8del** [comment] 2022-11-16 03:09
Thank you for responding. :) 

In 1.x `case confirmSignInWithSMSMFACode(AuthCodeDeliveryDetails, AdditionalInfo?)` handles SMS and softwareToken whereas in 2.x it returns an AuthError.

**Comment by harsh62** [comment] 2022-11-16 03:20
I am still unsure how 1.x can handle the signIn response, because the code path doesn't have `softwareTokenMfa` as an implemented case.

```
extension SignInResult {

    func toAmplifyAuthSignInStep() throws -> AuthSignInStep {
        switch signInState {
        case .signedIn:
            return .done
        case .smsMFA:
            let deliveryDetails = AuthCodeDeliveryDetails(destination: .sms(codeDetails?.destination))
            return .confirmSignInWithSMSMFACode(deliveryDetails, parameters)
        case .customChallenge:
            return .confirmSignInWithCustomChallenge(parameters)
        case .newPasswordRequired:
            return .confirmSignInWithNewPassword(parameters)
        default:
            throw (AuthError.unknown("AWSMobileClient auth state is not handled"))
        }
    }
}
```

Can you share your implementation details? So that I can try to reproduce on my end.

**Comment by harsh62** [comment] 2022-11-16 03:25
Can you enable verbose logging and share the request and response for sign in redacted any sensitive information.
``` 
            AWSDDLog.sharedInstance.add(AWSDDTTYLogger())
            AWSDDLog.sharedInstance.logLevel = .verbose
```
and you would need to import AWSCore
```
import AWSCore
```

I would like to understand the response in more detail.

**Comment by rpatel8del** [comment] 2022-11-16 03:38
Can I email you the response? Don't want to accidentally post anything here that I should've redacted and missed. :)

**Comment by harsh62** [comment] 2022-11-16 03:40
Can you post this on our [discord channel](https://discord.com/channels/705853757799399426/707328996995760179) and we can have follow up conversations there to further investigate into this matter?

**Comment by rpatel8del** [comment] 2022-11-16 03:42
Yup, that works.

**Comment by rpatel8del** [comment] 2022-11-27 23:01
When will this fix be released?

**Comment by royjit** [comment] 2023-03-10 18:01
We are actively working on providing TOTP support for Amplify v2, closing this ticket as duplicate. Please follow https://github.com/aws-amplify/amplify-swift/issues/938 for future updates.

**Closed by royjit** 2023-03-10 18:01 UTC
Labels: bug, auth, follow up
