### ISSUE TITLE
Auth - After I kill the app I am always logged out

### ISSUE THREAD

**Issue by DanielZanchi** [aws-amplify/amplify-swift#2715] opened 2023-01-28 10:33 UTC
### Describe the bug

After I do a Social sign-in (OAuth) and I kill the app, once I open the app I am not logged in.

I login:
```
		do {
			let options = AuthWebUISignInRequest.Options(scopes: ["openid", "email", "profile", "aws.cognito.signin.user.admin"], pluginOptions: AuthWebUISignInRequest.Options.preferPrivateSession())
			let signInResult = try await Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: window, options: options)
			if signInResult.isSignedIn {
				print("Sign in succeeded")
			}
			return signInResult.isSignedIn
		} catch let error as AuthError {
			DZError("Error in signin", error:error)
			return false
		} catch {
			DZError("Error in signin", error:error)
			return false
		}
```

After I kill my app. 
On launch, after Amplify configuration I call:
`let session = try await Amplify.Auth.fetchAuthSession()`
returning :
_session.isSignedIn_ always equals to **_false_**

### Steps To Reproduce

```swift
- Open the app
- sign in with signInWithWebUI
- check if I am signed in calling Amplify.Auth.fetchAuthSession() - i am signed in
- I kill the app
- I open the app again
- I configure Amplify
- I call Amplify.Auth.fetchAuthSession() - I am not signed in
```

### Expected behavior

After killing the app I should be signed in since I did the login in the previous session.

### Amplify Framework Version

2.3.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.5

### CLI version

10.6.2

### Xcode version

14.2

### Is this a regression?

No

### Device

iPhone 13 pro

### iOS Version

ios 16.3

**Comment by phantumcode** [comment] 2023-01-30 22:06
@DanielZanchi Your signed session is not retained as a result of using the plugin option `AuthWebUISignInRequest.Options.preferPrivateSession()` which causes web sessions to be private.

Please try removing the `AuthWebUISignInRequest.Options.preferPrivateSession()`.

**Comment by ameter** [comment] 2023-02-03 23:11
@DanielZanchi We have not been able to reproduce this issue.  We tried signing in with your example code and then force closing the app, and upon restarting the app and calling `let session = try await Amplify.Auth.fetchAuthSession()`, `session.isSignedIn` was consistently `true` and credentials were available.

A couple things to try...
- Please try running on a fresh simulator (select Device... Erase all Contents and Settings from the simulator menu before running the app) to rule out any sort of bad keychain state issue.
- Try upgrading to the latest version of amplify-swift, v2.3.2.  Although unlikely, this version included [one fix](https://github.com/aws-amplify/amplify-swift/pull/2687) that could possibly be related, depending on how and where you're calling `Amplify.Auth.fetchAuthSession()`
- Confirm that you're not calling `signOut` when the app enters the background or is terminated.

Incidentally, I noticed that your signIn method is not correctly setting `preferPrivateSession`.  This is not related to your issue, but should be updated to achieve the intended behavior. In this case, `pluginOptions` should be an instance of `AWSAuthWebUISignInOptions` Here's an example of how you could update your signIn method to set it:
```
import AWSCognitoAuthPlugin
// ...
let options = AuthWebUISignInRequest.Options(
    scopes: ["openid", "email", "profile", "aws.cognito.signin.user.admin"],
    pluginOptions: AWSAuthWebUISignInOptions(preferPrivateSession: true)
)
```

**Comment by ameter** [comment] 2023-02-23 20:45
Closing due to no response.  Please reopen if this is still an issue.

**Closed by ameter** 2023-02-23 20:45 UTC
Labels: pending-response, auth, closing soon, not-reproducible

**Comment by anand-OSM** [comment] 2024-04-03 12:26
Having same issue
