### ISSUE TITLE
Getting Error : Not able to get user state and User Attributes after successfull login.

### ISSUE THREAD

**Issue by gitton** [aws-amplify/amplify-swift#2291] opened 2022-09-12 15:17 UTC
### Describe the bug

I am getting Error, after the user successfully login from iOS App.
Issues : 
1. Method

```swift
Amplify.Auth.fetchAuthSession { result in
        switch result {
        case .success(let session):
            print("Is user signed in - \(session.isSignedIn)")
        case .failure(let error):
            print("Fetch session failed with error \(error)")
        }
    }
```
 Here the session is returning as true for (session.isSignedIn)
2. Method `Amplify.Auth.getCurrentUser() ` returning nil 
3. returning error 
: "Amplify Fetching user attributes failed with error AuthError: Could not fetch attributes, there is no user signed in to the Auth category
Recovery suggestion: SignIn to Auth category by using one of the sign-in methods and then call user attributes apis "

```swift
Amplify.Auth.fetchUserAttributes() { result in
        switch result {
        case .success(let attributes):
            print("User attributes - \(attributes)")
        case .failure(let error):
            print("Fetching user attributes failed with error \(error)")
        }
    }
```

### Steps To Reproduce

After user sucessfully login with amplify api, Amplify API does not work as expected

```swift
Amplify.Auth.signInWithWebUI(presentationAnchor: vc.view.window!){ result in
            switch result {
                case .success:
                print("\(self.TAG) Sign in succeeded")
                case .failure(let error):
                print("\(self.TAG) Sign in failed \(error)")
                }
        }
```

### Expected behavior

Return user attributes and states

1. return AuthUser Property from

```swift
Amplify.Auth.getCurrentUser() 
  ```

2. get user attributes from

```swift
Amplify.Auth.fetchUserAttributes() { result in
        switch result {
        case .success(let attributes):
            print("User attributes - \(attributes)")
        case .failure(let error):
            print("Fetching user attributes failed with error \(error)")
        }
    }
```

### Amplify Framework Version

1.28.0

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

manual

### Xcode version

13.4.1

### Relevant log output

```txt
Amplify Is user signed in - true
Amplify Fetching user attributes failed with error AuthError: Could not fetch attributes, there is no user signed in to the Auth category
Recovery suggestion: SignIn to Auth category by using one of the sign in methods and then call user attributes apis
```

### Is this a regression?

No

### Device

iPhone 13 Pro

### iOS Version

ios 15.5

**Comment by gitton** [comment] 2022-09-12 15:51
@harsh62  Thank you for your response. 

Please find amplifyconfiguration.json. Feel free to create new user and test
```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "SampleApp": {
                    "endpointType": "GraphQL",
                    "endpoint": "https://27xj7vwqnzbsbatuywzr74u24m.appsync-api.us-east-1.amazonaws.com/graphql",
                    "region": "us-east-1",
                    "authorizationType": "API_KEY",
                    "apiKey": "da2-cwzecdxdevfnbdfz6sadwdcn5i"
                }
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "https://27xj7vwqnzbsbatuywzr74u24m.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "API_KEY",
                        "ApiKey": "da2-cwzecdxdevfnbdfz6sadwdcn5i",
                        "ClientDatabasePrefix": "SampleApp_API_KEY"
                    },
                    "SampleApp_AWS_IAM": {
                        "ApiUrl": "https://27xj7vwqnzbsbatuywzr74u24m.appsync-api.us-east-1.amazonaws.com/graphql",
                        "Region": "us-east-1",
                        "AuthMode": "AWS_IAM",
                        "ClientDatabasePrefix": "SampleApp_AWS_IAM"
                    }
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "us-east-1:ab09255b-13ec-47fb-b863-208370e3772a",
                            "Region": "us-east-1"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "us-east-1_YzFpCSndz",
                        "AppClientId": "6uf43jqs99a2tijl9qqd7ke1b6",
                        "Region": "us-east-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH",
                        "OAuth": {
                                                   "WebDomain": "sample-app-stage.auth.us-east-1.amazoncognito.com",
                                                   "AppClientId": "3g0nagu8vl5d2qu5k7tuaf6vi2",
                                                   "SignInRedirectURI":"myapp://signin",
                                                   "SignOutRedirectURI": "myapp://signout",
                                                   "Scopes": ["email","openid"]
                                               },
                        "socialProviders": [],
                        "usernameAttributes": [
                            "EMAIL"
                        ],
                        "signupAttributes": [],
                        "passwordProtectionSettings": {
                            "passwordPolicyMinLength": 8,
                            "passwordPolicyCharacters": [
                                "REQUIRES_LOWERCASE",
                                "REQUIRES_NUMBERS",
                                "REQUIRES_SYMBOLS",
                                "REQUIRES_UPPERCASE"
                            ]
                        },
                        "mfaConfiguration": "OFF",
                        "mfaTypes": [
                            "SMS"
                        ],
                        "verificationMechanisms": [
                            "EMAIL"
                        ]
                    }
                }
            }
        }
    }
}

```

Response with respect to each method 

result of signInWithWebUI -> success

1. SignInWithWebUI - Success
2. getCurrentUser - Nil
3. FetchAuthSession - success (callback is success with isSignedIn -> true)
4. FetchAttributes - fail (error -> Fetching user attributes failed with error AuthError: Could not fetch attributes, there is no user signed in to the Auth category
Recovery suggestion: SignIn to Auth category by using one of the sign in methods and then call user attributes apis

**Comment by harsh62** [comment] 2022-09-16 18:24
Closing the issue. @gitton confirmed it was a configuration error on discord.

**Comment by gitton** [comment] 2022-09-16 18:42
@harsh62 did not understand. Could you mention where the configuration was wrong? Could not find the details on discord.

**Comment by harsh62** [comment] 2022-09-16 19:24
@gitton I am really sorry for the confusion. You are correct. Let me investigate this issue. Reopened.

**Comment by gitton** [comment] 2022-09-17 07:33
@harsh62  Thank you

**Comment by sanv725** [comment] 2022-10-29 18:11
@gitton Hi, I know it's been a while since you opened this issue but we're running this same issue on our iOS app currently. I see that you closed this issue but any chance it was closed because you were able to find a solution to it? If so, could you please help out and let me know how you were able to fix this issue?

**Comment by harsh62** [comment] 2022-11-01 19:57
@sanv725 
This issue came up when different AppClientID is used for HostedUI and UserPool. This configuration currently is not supported and breaks the aws-sdk-ios AWSMobileClient implementation. 

I'll reopen the issue for our team to prioritize the fix.

**Comment by harsh62** [comment] 2022-11-03 22:35
Closing. This is no longer an issue in Amplify 2.0.

**Closed by harsh62** 2022-11-03 22:35 UTC
Labels: bug, auth
