### ISSUE TITLE
Having issue with refresh token, getting Nil while calling awsmobileclient.default().gettokens in swift 

### ISSUE THREAD

**Issue by abdurrazax** [aws-amplify/amplify-swift#3456] opened 2023-12-20 07:47 UTC
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Step

GetToken

### Status

Auth error

### Issue or question

while calling this method in swift on Xcode "awsmobileclient.default().gettokens" I am getting nil value. 
I am calling after the successful login with Amplify.Auth.signIn 
after that when I am trying to call any mutation I'm getting Auth error 

### Error message

1. AWSMobileClient.AWSMobileClientError error 26.
2. Auth error. User is not signed in.

**Comment by arundna** [comment] 2024-01-04 19:41
@abdurrazax - Apologies for the delay! I'm transferring this to our Swift repository for better assistance.

**Comment by ruisebas** [comment] 2024-01-04 19:43
Duplicate of https://github.com/aws-amplify/amplify-swift/issues/3431, closing.

**Closed by ruisebas** 2024-01-04 19:43 UTC
