### ISSUE TITLE
Upload image to s3 bucket using cognito login user

### ISSUE THREAD

**Issue by bhavik45** [aws-amplify/amplify-swift#2767] opened 2023-02-14 13:14 UTC
### Describe the bug

We don’t want to add client id and secret in code. Is there any other way to upload image to s3 bucket wth using cognito logged in user?

I can use the below method -

```
Amplify.Storage.uploadFile(key: fileName, local: fileURL, options: options) { progress in
    print("Progress: \(progress)")
    
} resultListener: { event in
    
    switch event {
        
    case let .success(data):
        print("Completed: \(data)”)
              
    case let .failure(storageError):
        print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
    }
              
}
```

But this method is not working after 30 mins of login. after approx 30 mins I am getting this error - 

```
Failed: Unexpected error occurred with message: Could not retreive AWS credentials, credential value is nil or empty.. This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:

file: /Users/system/Documents/demo/Pods/Amplify/Amplify/Categories/Auth/Error/AuthError.swift

function: recoverySuggestion

line: 80
```

Everyting is working fine if I set defaultServiceConfiguration to AWSService manager. like this -

```
let credentialProvider = AWSCognitoCredentialsProvider(regionType: region, identityPoolId: “region:xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
if let configuration = AWSServiceConfiguration(region: region, credentialsProvider: credentialProvider) {
     AWSServiceManager.default().defaultServiceConfiguration = configuration
}
```

In this configuration I had to set identity pool id inside the code. Is it safe/secure to put identityPoolId inside code like this to configure?
I am not sure why I am getting this error after approx 30 mins. 

Any suggestion will be helpful.

### Steps To Reproduce

```swift
No specific steps. Just upload a file to awsS3 using amplify.storage method after 30 mins of login and getting the error.
```

### Expected behavior

Should upload image without error.

### Amplify Framework Version

1.22.1

### Amplify Categories

Storage

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

4.52.0

### Xcode version

14.2

### Is this a regression?

Yes

### Device

All devices. Tested in iPhone 13 and simulator

### iOS Version

16.2

### Specific to simulators

No

### Additional context

Here's the versions of all the installed pods -

  - Amplify (1.22.1):
    - Amplify/Default (= 1.22.1)
  - Amplify/Default (1.22.1)
  - AmplifyPlugins/AWSAPIPlugin (1.22.1):
    - AppSyncRealTimeClient (~> 1.8)
    - AWSCore (~> 2.27.0)
    - AWSPluginsCore (= 1.22.1)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.22.1):
    - AWSAuthCore (~> 2.27.0)
    - AWSCognitoIdentityProvider (~> 2.27.0)
    - AWSCognitoIdentityProviderASF (~> 2.27.0)
    - AWSCore (~> 2.27.0)
    - AWSMobileClient (~> 2.27.0)
    - AWSPluginsCore (= 1.22.1)
  - AmplifyPlugins/AWSDataStorePlugin (1.22.1):
    - AWSCore (~> 2.27.0)
    - AWSPluginsCore (= 1.22.1)
    - SQLite.swift (= 0.12.2)
  - AmplifyPlugins/AWSS3StoragePlugin (1.22.1):
    - AWSCore (~> 2.27.0)
    - AWSPluginsCore (= 1.22.1)
    - AWSS3 (~> 2.27.0)
  - AppSyncRealTimeClient (1.10.0):
    - Starscream (~> 4.0.4)
  - AWSAppSync (3.6.1):
    - AppSyncRealTimeClient (~> 1.7)
    - AWSCore (~> 2.27.0)
    - ReachabilitySwift (= 5.0.0)
    - SQLite.swift (~> 0.12.2)
  - AWSAuthCore (2.27.15):
    - AWSCore (= 2.27.15)
  - AWSCognitoIdentityProvider (2.27.15):
    - AWSCognitoIdentityProviderASF (= 2.27.15)
    - AWSCore (= 2.27.15)
  - AWSCognitoIdentityProviderASF (2.27.15):
    - AWSCore (= 2.27.15)
  - AWSCore (2.27.15)
  - AWSMobileClient (2.27.15):
    - AWSAuthCore (= 2.27.15)
    - AWSCognitoIdentityProvider (= 2.27.15)
    - AWSCognitoIdentityProviderASF (= 2.27.15)
    - AWSCore (= 2.27.15)
  - AWSPluginsCore (1.22.1):
    - Amplify (= 1.22.1)
    - AWSCore (~> 2.27.0)
  - AWSS3 (2.27.15):
    - AWSCore (= 2.27.15)

**Comment by phantumcode** [comment] 2023-03-03 19:09
@bhavik45 I was not able to reproduce this issue.  I was able to login, wait for 60 minutes, start and then complete an s3 upload.  I am using the latest released amplify library (Amplify V1 1.29.0 and Amplify V2 2.4.0)

Can you help with provide additional information on your current authentication configuration? What is currently configure in `amplifyconfiguration.json`? Are using both Cognito identity pool and user pool? What is the token session expiration you've configured for your app?

Can you enable verbose logging and attach the console log output?
```swift
Amplify.Logging.logLevel = .verbose
```

Does the failure occur immediately at the start of upload? Does it fail for other file types or is the image a large file that needs to use multipart upload?  Do you see the same failure with any other Amplify categories?

**Comment by phantumcode** [comment] 2023-03-10 18:29
@bhavik45 are you still still experiencing this issue? If so, please provide additional details requested from my previous comment to help with troubleshooting the issue.

**Comment by bhavik45** [comment] 2023-03-14 13:21
Sorry for the late response @phantumcode 

I am facing this randomly. I couldn't Identify the case. But this happened after I uploaded or loaded the image from my private s3 bucket. It worked fine for 10 mins after loading images, but it started showing the error message. I logged out and logged back in but still, the error was the same. Then I killed the application and relaunched it and it started working again.

Here's the configuration I've added in my app delegate - 

```
let serviceConfig = AWSServiceConfiguration(region: AWSRegionType.APNortheast2, credentialsProvider: nil)
        let poolConfig = AWSCognitoIdentityUserPoolConfiguration(clientId: UserPoolConfigCredentials.clientId, clientSecret: UserPoolConfigCredentials.clientSecret, poolId: UserPoolConfigCredentials.poolId)
        
        AWSCognitoIdentityUserPool.register(with: serviceConfig, userPoolConfiguration: poolConfig, forKey: "CognitoUserPool")
        self.poolUser = AWSCognitoIdentityUserPool(forKey: "CognitoUserPool")

        let credentialProvider = AWSCognitoCredentialsProvider(regionType: .APNortheast2, identityPoolId: UserPoolConfigCredentials.identityPoolId)
        if let configuration = AWSServiceConfiguration(region: .APNortheast2, credentialsProvider: credentialProvider) {
            AWSServiceManager.default().defaultServiceConfiguration = configuration
        }
        
        self.poolUser?.delegate = self
```

Here's amplify configuration - 

```
func configureAmplify() {
        
        do {
            // You can choose the directory in which AppSync stores its persistent cache databases
            let cacheConfiguration = try AWSAppSyncCacheConfiguration()
            // AppSync configuration & client initialization
            
            let appSyncServiceConfig = try AWSAppSyncServiceConfig()
            
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: appSyncServiceConfig,  userPoolsAuthProvider: {

                class MyCognitoUserPoolsAuthProvider : AWSCognitoUserPoolsAuthProviderAsync {

                    func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
                        if let username = UserDefaults.standard.value(forKey: UserDefaultsKey.kLoginUsername) as? String, username != "" {
                            let getUser = appDelegate.poolUser?.getUser(username)

                            getUser?.getSession().continueWith(block: { (task) -> Any? in
                                if let result = task.result {
                                    callback(result.idToken?.tokenString, nil)
                                    
                                } else {
                                    let error = (task.error as? NSError)
                                    if error?.code == 400 {
                                        appInstance.redirectToLoginForInvalidSession()
                                        callback(nil, task.error)
                                    } else {
                                        callback(nil, task.error)
                                    }
                                    
                                }
                                return task
                            })
                            
                        } else {
                            
                            AWSMobileClient.default().getTokens { (tokens, error) in
                                if error != nil {
                                    callback(nil, error)
                                } else {
                                    callback(tokens?.idToken?.tokenString, nil)
                                }
                            }
                        }
                        
                    }
                }
                return MyCognitoUserPoolsAuthProvider()}(), cacheConfiguration: cacheConfiguration)
            
            appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)

            appSyncClient?.apolloClient?.cacheKeyForObject = { $0["id"] }
            _ = AppSyncManager.sharedInstance
            
            //init AWSS3 Manager class
            _ = AWSS3Manager.sharedInstance
            
        } catch {
            print("Error initializing appsync client. \(error)")
        }
    }

```

For sign in I've used this method - 

```
let user = AWSCognitoIdentityUserPool(forKey: "CognitoUserPool")
appDelegate.poolUser = user
            
let getUser = appDelegate.poolUser?.getUser(username)
getUser?.getSession(username, password: password, validationData: nil)
```

My amplifyconfiguration.json looked like this -

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "hubFleetApi": {
                    "endpointType": "",
                    "endpoint": "",
                    "region": "",
                    "authorizationType": ""        
        }      
      }    
    }  
  },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {
            
          }        
        },
                "AppSync": {
                    "Default": {
                        "ApiUrl": "",
                        "Region": "",
                        "AuthMode": "",
                        "ClientDatabasePrefix": ""          
          }        
        },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "",
                            "Region": ""            
            }          
          }        
        },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "",
                        "AppClientId": "",
                        "Region": "",
                        "AppClientSecret": ""          
          }        
        },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": ""          
          }        
        },
                "S3TransferUtility": {
                    "Default": {
                        "Bucket": "",
                        "Region": ""          
          }        
        }      
      }    
    }  
  },
    "storage": {
        "plugins": {
            "awsS3StoragePlugin": {
                "bucket": "",
                "region": "",
                "defaultAccessLevel": "guest"      
      }    
    }  
  }
}
```
Please let me know if you need any other details.

Thank you.

**Comment by phantumcode** [comment] 2023-03-24 15:46
@bhavik45 Can you explain your use case for using Auth, Storage and API?  It looks like there are a few things that are unnecessary in your setup that can be simplified depending on your need and use case.

For example,

configuring amplify can be this:

```swift
        let authPlugin = AWSCognitoAuthPlugin()
        let storagePlugin = AWSS3StoragePlugin()
        let apiPlugin = AWSAPIPlugin()
        do {
            try Amplify.add(plugin: authPlugin)
            try Amplify.add(plugin: storagePlugin)
            try Amplify.add(plugin: apiPlugin)
            try Amplify.configure()
            print("Initialized Amplify");
        } catch {
            assert(false, "Could not initialize Amplify: \(error)")
        }
    }
```

Auth signin:

```swift
    func signIn(username: String, password: String) -> AnyCancellable {
        Amplify.Auth.signIn(username: username, password: password)
            .resultPublisher
            .sink {
                if case let .failure(authError) = $0 {
                    print("Sign in failed \(authError)")
                }
            }
            receiveValue: { _ in
                print("Sign in succeeded")
            }
    }
```

Storage upload:
```swift
        let storageOperation = Amplify.Storage.uploadData(
            key: key,
            local: fileUrl,
            options: options,
            progressListener: { progress in
                print("Progress: \(progress)")
            }, resultListener: { event in
                switch event {
                case .success(let data):
                    print("Completed: \(data)")
                case .failure(let storageError):
                    print("Failed: \(storageError.errorDescription). \(storageError.recoverySuggestion)")
                }
            }
        )
        storageOperation.start()
```

For additional details, please refer to the Amplify V1 documentation: https://docs.amplify.aws/lib-v1/q/platform/ios/

**Comment by phantumcode** [comment] 2023-04-14 17:28
@bhavik45 Were you able to resolve the issues? If not, please see my previous question/comment.

**Comment by phantumcode** [comment] 2023-05-05 17:49
Closing this issue, please re-open this issue if you are still seeing the issue.

**Closed by phantumcode** 2023-05-05 17:49 UTC
Labels: pending-response, storage, auth, closing soon, not-reproducible
