### ISSUE TITLE
Metadata is not uploaded with the Storage.uploadFile() function in Amplify v2

### ISSUE THREAD

**Issue by benj20** [aws-amplify/amplify-swift#2744] opened 2023-02-06 16:02 UTC
### Describe the bug

With Amplify v2 when I upload a file with the `Storage.uploadFile()` function the metadata passed in the `options` parameter is not in the s3.
While everything works fine with Amplify v1.

```
let options = StorageUploadFileRequest.Options(
    accessLevel: .guest,
    targetIdentityId: nil,
    metadata: ["test": "test"],
    contentType: nil,
    pluginOptions: nil
)

let uploadTask = Amplify.Storage.uploadFile(
    key: self.getVideoKey(video: video),
    local: url,
    options: options
)
```

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Add metadata in "options" parameter
2. Upload file
3. No metadata in s3
```

### Expected behavior

The ability to add metadata to the file. 

### Amplify Framework Version

2.3.2

### Amplify Categories

Storage

### Dependency manager

Swift PM

### Swift version

5.7.1

### CLI version

I do not use it

### Xcode version

14.1

### Is this a regression?

Yes

### Device

iPhone 12 pro (not simulator)

### iOS Version

iOS 16.2

**Comment by phantumcode** [comment] 2023-02-23 18:54
@benj20 Thanks for reporting this issue.  I was able to reproduce the issue and identify where the problem is occurring.  We'll work on a fix for the issue.

**Comment by phantumcode** [comment] 2023-02-23 23:28
The Storage plugin in Amplify Swift V2 was ignoring/dropping the metadata in the plugin request options.  Adding the metadata back causes a 403 http response.  Submitted an issue to AWS Swift SDK for additional help: https://github.com/awslabs/aws-sdk-swift/issues/892

**Comment by phantumcode** [comment] 2023-10-19 14:56
Fixed for issue is available in latest release [v2.20.1](https://github.com/aws-amplify/amplify-swift/releases/tag/2.20.1)

**Comment by lailabecker** [comment] 2023-10-20 09:05
Hello

The fix works for me and the metadata is uploaded but now the the `x-amz-meta-` prefix is inserted twice, i.e. I see `x-amz-meta-x-amz-meta-field-name` in the AWS console. Can you have a look at that?

**Comment by atierian** [comment] 2023-10-20 13:11
Quick update - we're reproduced this, identified the fix, and are working on getting it released ASAP. 
We'll let you know once it's released.

**Comment by lailabecker** [comment] 2023-11-01 09:09
Thanks! It looks good now with v2.21.1

**Closed** 2023-11-01 10:59 UTC
Labels: bug, storage, pending-release, feature-parity
